/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TileViewImport } from './routes/tileView'
import { Route as IndexImport } from './routes/index'
import { Route as PhotoDetailsDateImport } from './routes/photoDetails.$date'

// Create/Update Routes

const TileViewRoute = TileViewImport.update({
  id: '/tileView',
  path: '/tileView',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PhotoDetailsDateRoute = PhotoDetailsDateImport.update({
  id: '/photoDetails/$date',
  path: '/photoDetails/$date',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tileView': {
      id: '/tileView'
      path: '/tileView'
      fullPath: '/tileView'
      preLoaderRoute: typeof TileViewImport
      parentRoute: typeof rootRoute
    }
    '/photoDetails/$date': {
      id: '/photoDetails/$date'
      path: '/photoDetails/$date'
      fullPath: '/photoDetails/$date'
      preLoaderRoute: typeof PhotoDetailsDateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tileView': typeof TileViewRoute
  '/photoDetails/$date': typeof PhotoDetailsDateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tileView': typeof TileViewRoute
  '/photoDetails/$date': typeof PhotoDetailsDateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tileView': typeof TileViewRoute
  '/photoDetails/$date': typeof PhotoDetailsDateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tileView' | '/photoDetails/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tileView' | '/photoDetails/$date'
  id: '__root__' | '/' | '/tileView' | '/photoDetails/$date'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TileViewRoute: typeof TileViewRoute
  PhotoDetailsDateRoute: typeof PhotoDetailsDateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TileViewRoute: TileViewRoute,
  PhotoDetailsDateRoute: PhotoDetailsDateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tileView",
        "/photoDetails/$date"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tileView": {
      "filePath": "tileView.tsx"
    },
    "/photoDetails/$date": {
      "filePath": "photoDetails.$date.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
